[workspace]
members = [
    "crates/sctransform-rs",
    "crates/sctransform-rs-cli",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
repository = "https://github.com/oriclabs/sctransform-rs"
homepage = "https://github.com/oriclabs/sctransform-rs"
rust-version = "1.75"

[profile.release]
lto = "thin"
codegen-units = 1
strip = "symbols"

